POST http://localhost:8080/login
Content-Type: application/json

{
  "username":"user3",
  "password":"password1"
}

###
GET http://localhost:8080/users?id=1
Content-Type: application/json
Authorization: axdvap9ixos


###
DELETE http://localhost:8080/users?id=22
Content-Type: application/json
Authorization: 87nxpdj17jd

###
GET http://localhost:8080/users?name=gord
Content-Type: application/json
Authorization: y8xkhqmw8co

###

PUT http://localhost:8080/users
Content-Type: application/json
Authorization: y8xkhqmw8co

{
  "name":"gordie",
  "age":43,
  "email":"raamsesy@hotmail.com",
  "workingPosition":2,
  "id":1
}
